Import Library

In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Persiapan Data

Membaca Dataset

In [2]:
train = pd.read_csv('data_training.csv')
test = pd.read_csv('data_testing.csv')

Menampilkan Dataset

In [3]:
train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.3,0.740,0.08,1.7,0.094,10.0,45.0,0.99576,3.24,0.50,9.8,5,1366
1,8.1,0.575,0.22,2.1,0.077,12.0,65.0,0.99670,3.29,0.51,9.2,5,103
2,10.1,0.430,0.40,2.6,0.092,13.0,52.0,0.99834,3.22,0.64,10.0,7,942
3,12.9,0.500,0.55,2.8,0.072,7.0,24.0,1.00012,3.09,0.68,10.9,6,811
4,8.4,0.360,0.32,2.2,0.081,32.0,79.0,0.99640,3.30,0.72,11.0,6,918
...,...,...,...,...,...,...,...,...,...,...,...,...,...
852,6.7,1.040,0.08,2.3,0.067,19.0,32.0,0.99648,3.52,0.57,11.0,4,1467
853,8.0,0.390,0.30,1.9,0.074,32.0,84.0,0.99717,3.39,0.61,9.0,5,1533
854,7.4,0.350,0.33,2.4,0.068,9.0,26.0,0.99470,3.36,0.60,11.9,6,1580
855,7.9,0.570,0.31,2.0,0.079,10.0,79.0,0.99677,3.29,0.69,9.5,6,1216
856,7.5,0.520,0.40,2.2,0.060,12.0,20.0,0.99474,3.26,0.64,11.8,6,1575

# Pembersihan Data

Cek Missing Value

In [4]:
train.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Id                      0
dtype: int64

In [5]:
test.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
Id                      0
dtype: int64

Memisahkan Fitur dan Target

In [6]:
X = train.drop('quality', axis=1)
y = train['quality']

Split Data

In [7]:
X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

Feature Scaling

In [8]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)

# Pembuatan Model

Membuat dan Melatih Model

In [9]:
model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

# Evaluasi Model

Evaluasi Model

In [10]:
y_pred = model.predict(X_val)

accuracy = accuracy_score(y_val, y_pred)

print("Accuracy Score:", accuracy)

Accuracy Score: 0.6046511627906976

In [11]:
cm = confusion_matrix(y_val, y_pred)

print(cm)

[[ 0  1  2  0  0]
 [ 0 47 20  0  0]
 [ 0 23 49  6  0]
 [ 0  2 11  8  0]
 [ 0  0  0  3  0]]

# Prediksi Data Uji

Prediksi Data Testing

In [12]:
X_test = test.copy()

In [13]:
X_test = scaler.transform(X_test)

In [14]:
test_pred = model.predict(X_test)

Membuat Hasil Prediksi

In [15]:
hasil = pd.DataFrame({
    'Id': test['Id'],
    'quality': test_pred
})

In [16]:
hasil

       Id  quality
0     222        5
1    1514        5
2     417        5
3     754        5
4     516        5
..    ...      ...
281  1147        6
282   296        5
283   170        5
284  1439        5
285   946        7

[286 rows x 2 columns]

Menyimpan File CSV

In [17]:
hasil.to_csv(
    'hasilprediksi_043.csv',
    index=False,
    sep=';'
)